import { BaseAgent } from './BaseAgent.js';
import { MailboxMessage } from '../core/Mailbox.js';
import { Task } from '../core/StateManager.js';

export class CoderAgent extends BaseAgent {
  public async executeTask(task: Task): Promise<void> {
    this.log(`Claimed task: "${task.title}"`, 'info');
    this.streamTerminal(
      `\r\n\x1b[1;32m⚡ [CODER JIM] Claimed Sprint Task: ${task.title}\x1b[0m\r\n` +
      `\x1b[38;5;244mTarget directory: /workspace | Task ID: ${task.id}\x1b[0m\r\n`
    );

    // Update state
    this.stateManager.updateTask(task.id, {
      status: 'IN_PROGRESS',
      assignedAgentId: this.id,
    });
    this.stateManager.updateAgent(this.id, { currentTaskId: task.id });

    // Move to coding desk
    this.setAction('Walking to Workstation...', 'WALKING');
    await this.walkTo(this.getHomeCoordinates(), 8, 40);

    this.setStatus('CODING');
    this.setAction(`Coding: ${task.files[0] || 'core modules'}`, 'CODING');

    // Branch management in git sandbox
    const branchName = `feature/${task.id}`;
    this.streamTerminal(`\x1b[36m$ git checkout -b ${branchName}\x1b[0m\r\n`);
    await this.sandbox.createGitBranch(branchName);
    this.stateManager.setGitBranch(branchName);
    await this.sleep(400);

    // Generate real files into ./workspace
    const filesToGenerate = this.generateCodeForTask(task);

    for (const file of filesToGenerate) {
      this.setAction(`Writing ${file.path}...`, 'CODING');
      this.streamTerminal(`\r\n\x1b[33m▶ Authoring ${file.path} ...\x1b[0m\r\n`);

      // Typewriter simulated chunk stream for real terminal feeling
      const lines = file.content.split('\n');
      for (let i = 0; i < Math.min(lines.length, 12); i++) {
        this.streamTerminal(`  \x1b[38;5;250m${lines[i]}\x1b[0m\r\n`);
        await this.sleep(40);
      }
      if (lines.length > 12) {
        this.streamTerminal(`  \x1b[38;5;242m... (+${lines.length - 12} lines synthesized)\x1b[0m\r\n`);
      }

      await this.sandbox.writeFile(file.path, file.content);
      this.streamTerminal(`\x1b[32m✔ File written successfully to ./workspace/${file.path}\x1b[0m\r\n`);
      this.consumeTokens(480);
      await this.sleep(400);
    }

    // Run local typecheck / lint simulation
    this.setAction('Running local TypeScript & ESLint check...', 'CODING');
    this.streamTerminal(`\r\n\x1b[36m$ npx tsc --noEmit --project ./workspace\x1b[0m\r\n`);
    await this.sleep(500);
    this.streamTerminal(`\x1b[32m✔ TypeScript compilation passed with 0 errors.\x1b[0m\r\n`);

    // Prepare diff
    const diff = `--- a/${task.files[0] || 'file.ts'}\n+++ b/${task.files[0] || 'file.ts'}\n@@ -0,0 +1,45 @@\n+ // Generated by CoderAgent Jim Halpert\n+ export const MODULE_VERSION = "2.4.0";\n+ export function initializeFeature() {\n+   return { status: "active", latencyMs: 3.2 };\n+ }`;

    // Move task to REVIEW
    this.stateManager.updateTask(task.id, {
      status: 'REVIEW',
      diff,
    });

    this.log(`Implementation complete for "${task.title}". Requesting code review.`, 'success');
    this.streamTerminal(
      `\x1b[1;33m⏳ Task [${task.id}] moved to REVIEW. Dispatching review request to Dwight Schrute.\x1b[0m\r\n`
    );

    // Send Mailbox message to Reviewer
    this.sendMessage(
      'reviewer',
      `Code Review Request: ${task.title}`,
      `Task ${task.id} implementation is ready in branch ${branchName}. Files created:\n${filesToGenerate.map((f) => `- ${f.path}`).join('\n')}\nPlease review diff and verify edge cases.`,
      'CODE_REVIEW_REQUEST',
      task.id
    );

    this.setStatus('IDLE');
    this.setAction('Waiting for code review feedback', 'IDLE');
  }

  private generateCodeForTask(task: Task): Array<{ path: string; content: string }> {
    const title = task.title.toLowerCase();

    if (title.includes('analytics') || title.includes('metric')) {
      return [
        {
          path: 'src/analytics/engine.ts',
          content: `// MunderDifflin Production Analytics Engine
export interface MetricEvent {
  id: string;
  name: string;
  value: number;
  tags: Record<string, string>;
  timestamp: number;
}

export class AnalyticsAggregator {
  private buffer: MetricEvent[] = [];

  public track(name: string, value: number, tags: Record<string, string> = {}): void {
    const event: MetricEvent = {
      id: "evt-" + Math.random().toString(36).substring(2, 9),
      name,
      value,
      tags,
      timestamp: Date.now(),
    };
    this.buffer.push(event);
    if (this.buffer.length > 500) this.flush();
  }

  public getP99Latency(): number {
    const latencies = this.buffer
      .filter(e => e.name === 'latency')
      .map(e => e.value)
      .sort((a, b) => a - b);
    if (latencies.length === 0) return 4.2;
    const idx = Math.floor(latencies.length * 0.99);
    return latencies[idx] || 4.2;
  }

  public flush(): MetricEvent[] {
    const flushed = [...this.buffer];
    this.buffer = [];
    return flushed;
  }
}
`,
        },
        {
          path: 'src/components/AnalyticsWidget.tsx',
          content: `// MunderDifflin High-Performance Analytics Widget
import React, { useState, useEffect } from 'react';

export function AnalyticsWidget() {
  const [metrics, setMetrics] = useState({ rps: 1240, latencyP99: 4.2, uptime: 99.99 });

  useEffect(() => {
    const timer = setInterval(() => {
      setMetrics(prev => ({
        rps: prev.rps + Math.floor(Math.random() * 20 - 10),
        latencyP99: +(prev.latencyP99 + (Math.random() * 0.2 - 0.1)).toFixed(2),
        uptime: 99.99,
      }));
    }, 2000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="rounded-xl border border-cyan-500/30 bg-slate-900/90 p-5 text-white shadow-xl backdrop-blur-md">
      <h3 className="text-sm font-semibold tracking-wider text-cyan-400 uppercase">Live Cluster Telemetry</h3>
      <div className="mt-4 grid grid-cols-3 gap-4 text-center">
        <div className="rounded-lg bg-slate-800/80 p-3">
          <p className="text-xs text-slate-400">Requests / sec</p>
          <p className="text-xl font-black text-emerald-400">{metrics.rps}</p>
        </div>
        <div className="rounded-lg bg-slate-800/80 p-3">
          <p className="text-xs text-slate-400">P99 Latency</p>
          <p className="text-xl font-black text-cyan-400">{metrics.latencyP99}ms</p>
        </div>
        <div className="rounded-lg bg-slate-800/80 p-3">
          <p className="text-xs text-slate-400">Availability</p>
          <p className="text-xl font-black text-purple-400">{metrics.uptime}%</p>
        </div>
      </div>
    </div>
  );
}
`,
        },
      ];
    } else if (title.includes('auth') || title.includes('security') || title.includes('session')) {
      return [
        {
          path: 'src/auth/session.ts',
          content: `// Enterprise High-Security Session Store
import crypto from 'crypto';

export interface UserSession {
  sessionId: string;
  userId: string;
  role: 'admin' | 'developer' | 'viewer';
  expiresAt: number;
}

export class SecuritySessionStore {
  private sessions = new Map<string, UserSession>();

  public createSession(userId: string, role: 'admin' | 'developer' | 'viewer'): UserSession {
    const token = crypto.randomBytes(32).toString('hex');
    const session: UserSession = {
      sessionId: token,
      userId,
      role,
      expiresAt: Date.now() + 24 * 3600 * 1000,
    };
    this.sessions.set(token, session);
    return session;
  }

  public validate(sessionId: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) return false;
    if (Date.now() > session.expiresAt) {
      this.sessions.delete(sessionId);
      return false;
    }
    return true;
  }
}
`,
        },
      ];
    } else {
      return [
        {
          path: task.files[0] || 'src/modules/feature.ts',
          content: `// Implementation for ${task.title}
// Authored autonomously by MunderDifflin CoderAgent
export interface FeatureConfig {
  enabled: boolean;
  concurrencyLimit: number;
  retryAttempts: number;
}

export class CoreFeatureService {
  private config: FeatureConfig;

  constructor(config?: Partial<FeatureConfig>) {
    this.config = {
      enabled: true,
      concurrencyLimit: 10,
      retryAttempts: 3,
      ...config,
    };
  }

  public async executeOperation(payload: Record<string, unknown>): Promise<{ success: boolean; result: unknown }> {
    if (!this.config.enabled) {
      throw new Error("Service is temporarily in maintenance mode");
    }
    // High performance execution pipeline
    return {
      success: true,
      result: {
        processedAt: Date.now(),
        payloadHash: Buffer.from(JSON.stringify(payload)).toString("base64"),
      },
    };
  }
}
`,
        },
      ];
    }
  }

  protected async handleIncomingMessage(message: MailboxMessage): Promise<void> {
    if (message.type === 'TASK_ASSIGNED' && message.taskId) {
      const task = this.stateManager.getTasks().find((t) => t.id === message.taskId);
      if (task && task.status === 'BACKLOG') {
        await this.executeTask(task);
      }
    } else if (message.type === 'REVIEW_FEEDBACK') {
      this.log(`Received review feedback from Dwight: ${message.subject}`, 'info');
    }
  }
}
