import {
  Agent,
  FileTreeNode,
  MailboxMessage,
  OfficeState,
  Task,
} from './types';

// In-Memory Virtual Workspace Filesystem
interface VirtualFile {
  path: string;
  relativePath: string;
  content: string;
}

const DEFAULT_VIRTUAL_FILES: Record<string, string> = {
  'README.md': `# 📦 Target Agent Sandbox Workspace

This directory is an isolated sandbox where the MunderDifflin multi-agent team authors code, creates branches, and executes test suites.

## Project Structure
- Source files generated by **CoderAgent** are placed here.
- Automated tests, builds, and git branches are verified by **DevOpsAgent**.
- Code diffs and quality reviews are managed by **ReviewerAgent**.

---
*Managed autonomously by MunderDifflin Client Orchestrator.*
`,
  'package.json': `{
  "name": "munder-sandbox-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "test": "vitest run --coverage",
    "build": "next build",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }
}
`,
  'src/analytics/engine.ts': `// MunderDifflin Production Analytics Engine
export interface MetricEvent {
  id: string;
  name: string;
  value: number;
  tags: Record<string, string>;
  timestamp: number;
}

export class AnalyticsAggregator {
  private buffer: MetricEvent[] = [];

  public track(name: string, value: number, tags: Record<string, string> = {}): void {
    const event: MetricEvent = {
      id: "evt-" + Math.random().toString(36).substring(2, 9),
      name,
      value,
      tags,
      timestamp: Date.now(),
    };
    this.buffer.push(event);
    if (this.buffer.length > 500) this.flush();
  }

  public getP99Latency(): number {
    const latencies = this.buffer
      .filter(e => e.name === 'latency')
      .map(e => e.value)
      .sort((a, b) => a - b);
    if (latencies.length === 0) return 4.2;
    const idx = Math.floor(latencies.length * 0.99);
    return latencies[idx] || 4.2;
  }

  public flush(): MetricEvent[] {
    const flushed = [...this.buffer];
    this.buffer = [];
    return flushed;
  }
}
`,
  'src/components/AnalyticsWidget.tsx': `// MunderDifflin High-Performance Analytics Widget
import React, { useState, useEffect } from 'react';

export function AnalyticsWidget() {
  const [metrics, setMetrics] = useState({ rps: 1420, latencyP99: 3.8, uptime: 99.99 });

  useEffect(() => {
    const timer = setInterval(() => {
      setMetrics(prev => ({
        rps: prev.rps + Math.floor(Math.random() * 20 - 10),
        latencyP99: +(prev.latencyP99 + (Math.random() * 0.2 - 0.1)).toFixed(2),
        uptime: 99.99,
      }));
    }, 2000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="rounded-xl border border-[#324536] bg-[#162119] p-5 text-[#f4f1ea] shadow-xl">
      <h3 className="text-xs font-semibold tracking-wider text-[#e9c46a] uppercase font-mono">Live Cluster Telemetry</h3>
      <div className="mt-3 grid grid-cols-3 gap-3 text-center font-mono">
        <div className="rounded-lg bg-[#111813] p-2.5 border border-[#28382c]">
          <p className="text-[10px] text-[#8e9c91]">RPS</p>
          <p className="text-lg font-bold text-[#52b788]">{metrics.rps}</p>
        </div>
        <div className="rounded-lg bg-[#111813] p-2.5 border border-[#28382c]">
          <p className="text-[10px] text-[#8e9c91]">P99 Latency</p>
          <p className="text-lg font-bold text-[#e9c46a]">{metrics.latencyP99}ms</p>
        </div>
        <div className="rounded-lg bg-[#111813] p-2.5 border border-[#28382c]">
          <p className="text-[10px] text-[#8e9c91]">SLA</p>
          <p className="text-lg font-bold text-[#84a98c]">{metrics.uptime}%</p>
        </div>
      </div>
    </div>
  );
}
`,
};

export class ClientOrchestrator {
  private state: OfficeState;
  private mailbox: MailboxMessage[] = [];
  private virtualFiles: Record<string, string> = { ...DEFAULT_VIRTUAL_FILES };
  private stateListeners: Array<(state: OfficeState) => void> = [];
  private terminalListeners: Array<(agentId: string, chunk: string) => void> = [];
  private mailboxListeners: Array<(message: MailboxMessage) => void> = [];
  private isBusy: boolean = false;
  private startTime: number = Date.now();

  constructor() {
    this.state = this.createInitialState();
  }

  private createInitialState(): OfficeState {
    const agents: Record<string, Agent> = {
      pm: {
        id: 'pm',
        name: "Michael 'PM' Scott",
        role: 'PLANNER',
        title: 'Lead Architect & Sprint Planner',
        persona:
          'Visionary product lead. Deconstructs requirements into atomic milestones and backlog tasks.',
        status: 'IDLE',
        avatarConfig: {
          skinColor: '#F5D0A9',
          hairColor: '#2D3748',
          shirtColor: '#3B82F6',
          pantsColor: '#1E293B',
          accessory: 'tie',
          hairStyle: 'slick',
        },
        coordinates: { x: 260, y: 190 },
        targetCoordinates: { x: 260, y: 190 },
        homeCoordinates: { x: 260, y: 190 },
        dimensions: { width: 32, height: 32 },
        currentAction: 'Reviewing sprint backlog',
        actionProgress: 100,
        currentTaskId: null,
        tokensUsed: 3840,
        costUsd: 0.0115,
        logs: ['[PM] OfficeDev simulation engine ready.'],
      },
      coder: {
        id: 'coder',
        name: "Jim 'Fullstack' Halpert",
        role: 'CODER',
        title: 'Senior Full-Stack Engineer',
        persona:
          'Elite 10x developer. Crafts clean, modular TypeScript, Next.js components, and backend microservices with rigorous type safety.',
        status: 'IDLE',
        avatarConfig: {
          skinColor: '#FCD34D',
          hairColor: '#78350F',
          shirtColor: '#10B981',
          pantsColor: '#334155',
          accessory: 'headphones',
          hairStyle: 'messy',
        },
        coordinates: { x: 420, y: 190 },
        targetCoordinates: { x: 420, y: 190 },
        homeCoordinates: { x: 420, y: 190 },
        dimensions: { width: 32, height: 32 },
        currentAction: 'At workstation',
        actionProgress: 100,
        currentTaskId: null,
        tokensUsed: 5920,
        costUsd: 0.0177,
        logs: ['[CODER] Local workspace loaded. Listening for assigned tasks.'],
      },
      reviewer: {
        id: 'reviewer',
        name: "Dwight 'QA' Schrute",
        role: 'REVIEWER',
        title: 'Staff Security & QA Reviewer',
        persona:
          'Ruthless quality gatekeeper. Audits every diff, scans for edge case vulnerabilities, and enforces architectural standards.',
        status: 'IDLE',
        avatarConfig: {
          skinColor: '#FDE68A',
          hairColor: '#451A03',
          shirtColor: '#F59E0B',
          pantsColor: '#1F2937',
          accessory: 'glasses',
          hairStyle: 'parted',
        },
        coordinates: { x: 580, y: 190 },
        targetCoordinates: { x: 580, y: 190 },
        homeCoordinates: { x: 580, y: 190 },
        dimensions: { width: 32, height: 32 },
        currentAction: 'Auditing security gates',
        actionProgress: 100,
        currentTaskId: null,
        tokensUsed: 2640,
        costUsd: 0.0079,
        logs: ['[REVIEWER] Security lint rules online. Ready for pull requests.'],
      },
      devops: {
        id: 'devops',
        name: "Pam 'DevOps' Beesly",
        role: 'DEVOPS',
        title: 'Lead SRE & Platform Engineer',
        persona:
          'Automation and platform master. Manages Git branching, executes test runners, and coordinates zero-downtime releases.',
        status: 'IDLE',
        avatarConfig: {
          skinColor: '#FED7AA',
          hairColor: '#B45309',
          shirtColor: '#EC4899',
          pantsColor: '#0F172A',
          accessory: 'badge',
          hairStyle: 'ponytail',
        },
        coordinates: { x: 740, y: 280 },
        targetCoordinates: { x: 740, y: 280 },
        homeCoordinates: { x: 740, y: 280 },
        dimensions: { width: 32, height: 32 },
        currentAction: 'Monitoring cluster status',
        actionProgress: 100,
        currentTaskId: null,
        tokensUsed: 3100,
        costUsd: 0.0093,
        logs: ['[DEVOPS] CI/CD runner listening for commits.'],
      },
    };

    const initialTasks: Task[] = [
      {
        id: 'task-101',
        title: 'Initialize Workspace Core & Routing',
        description: 'Set up file structure, environment configs, and routing engine in ./workspace.',
        status: 'DONE',
        assignedAgentId: 'coder',
        priority: 'HIGH',
        files: ['package.json', 'README.md'],
        createdAt: Date.now() - 3600000,
        completedAt: Date.now() - 3200000,
        testResults: { passed: true, output: '100% test coverage passed.' },
        reviewNotes: ['Clean foundation, approved by Dwight.'],
      },
      {
        id: 'task-102',
        title: 'Setup High-Speed Event Bus & Telemetry',
        description: 'Implement real-time agent state sync and terminal log streaming.',
        status: 'DONE',
        assignedAgentId: 'devops',
        priority: 'MEDIUM',
        files: ['src/analytics/engine.ts'],
        createdAt: Date.now() - 3000000,
        completedAt: Date.now() - 2500000,
        testResults: { passed: true, output: 'Latency < 4.2ms verified.' },
        reviewNotes: ['Telemetry verified.'],
      },
    ];

    return {
      agents,
      tasks: initialTasks,
      metrics: {
        totalTokens: 15500,
        totalCost: 0.0464,
        activeAgents: 0,
        completedTasks: 2,
        totalTasks: 2,
        uptimeSeconds: 0,
        gitBranch: 'main',
        currentProject: 'MunderDifflin / Core Workspace',
        isPaused: false,
      },
      recentLogs: [
        {
          id: 'log-1',
          agentId: 'pm',
          agentName: "Michael 'PM' Scott",
          text: 'OfficeDev Client-Side Simulation Active. Ready for sprint goals.',
          timestamp: Date.now() - 10000,
          level: 'info',
        },
      ],
      rooms: {
        conference: {
          id: 'conference',
          name: 'Conference Room',
          coordinates: { x: 180, y: 140 },
          dimensions: { width: 220, height: 170 },
          color: '#a6825c',
        },
        devDesks: {
          id: 'devDesks',
          name: 'Engineering Desks',
          coordinates: { x: 420, y: 190 },
          dimensions: { width: 460, height: 180 },
          color: '#d6d0c2',
        },
        cafe: {
          id: 'cafe',
          name: 'Break Lounge',
          coordinates: { x: 140, y: 340 },
          dimensions: { width: 170, height: 120 },
          color: '#e8e4db',
        },
        server: {
          id: 'server',
          name: 'Server Cluster',
          coordinates: { x: 740, y: 280 },
          dimensions: { width: 140, height: 180 },
          color: '#171e19',
        },
      },
      furniture: {
        pmDesk: { id: 'pmDesk', name: 'PM Desk', coordinates: { x: 260, y: 190 }, dimensions: { width: 90, height: 36 } },
        coderDesk: { id: 'coderDesk', name: 'Coder Desk', coordinates: { x: 420, y: 190 }, dimensions: { width: 90, height: 36 } },
        qaDesk: { id: 'qaDesk', name: 'QA Desk', coordinates: { x: 580, y: 190 }, dimensions: { width: 90, height: 36 } },
        confTable: { id: 'confTable', name: 'Conference Table', coordinates: { x: 180, y: 140 }, dimensions: { width: 160, height: 80 } },
      },
    };
  }

  public getState(): OfficeState {
    this.state.metrics.uptimeSeconds = Math.floor((Date.now() - this.startTime) / 1000);
    return this.state;
  }

  public getMailbox(): MailboxMessage[] {
    return [...this.mailbox];
  }

  public subscribeState(listener: (state: OfficeState) => void): () => void {
    this.stateListeners.push(listener);
    listener(this.getState());
    return () => {
      this.stateListeners = this.stateListeners.filter((l) => l !== listener);
    };
  }

  public subscribeTerminal(listener: (agentId: string, chunk: string) => void): () => void {
    this.terminalListeners.push(listener);
    return () => {
      this.terminalListeners = this.terminalListeners.filter((l) => l !== listener);
    };
  }

  public subscribeMailbox(listener: (message: MailboxMessage) => void): () => void {
    this.mailboxListeners.push(listener);
    return () => {
      this.mailboxListeners = this.mailboxListeners.filter((l) => l !== listener);
    };
  }

  private notifyState(): void {
    const state = this.getState();
    const active = Object.values(state.agents).filter((a) => a.status !== 'IDLE').length;
    state.metrics.activeAgents = active;
    for (const l of this.stateListeners) {
      try {
        l(state);
      } catch {}
    }
  }

  private emitTerminal(agentId: string, chunk: string): void {
    for (const l of this.terminalListeners) {
      try {
        l(agentId, chunk);
      } catch {}
    }
  }

  private sendMailboxMessage(
    from: string,
    to: string,
    subject: string,
    content: string,
    type: any = 'GENERAL',
    taskId?: string
  ): void {
    const msg: MailboxMessage = {
      id: `msg-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      from,
      to,
      subject,
      content,
      timestamp: Date.now(),
      type,
      taskId,
      read: false,
    };
    this.mailbox.unshift(msg);
    for (const l of this.mailboxListeners) {
      try {
        l(msg);
      } catch {}
    }
  }

  private sleep(ms: number): Promise<void> {
    return new Promise((r) => setTimeout(r, ms));
  }

  private async animateWalk(
    agentId: string,
    target: { x: number; y: number },
    steps: number = 8,
    delayMs: number = 50
  ): Promise<void> {
    const agent = this.state.agents[agentId];
    if (!agent) return;
    const current = { ...agent.coordinates };
    agent.status = 'WALKING';
    agent.targetCoordinates = target;

    const dx = (target.x - current.x) / steps;
    const dy = (target.y - current.y) / steps;

    for (let i = 1; i <= steps; i++) {
      agent.coordinates = {
        x: Math.round(current.x + dx * i),
        y: Math.round(current.y + dy * i),
      };
      this.notifyState();
      await this.sleep(delayMs);
    }

    agent.coordinates = target;
    this.notifyState();
  }

  public async startSprint(prompt: string): Promise<void> {
    if (this.isBusy) return;
    this.isBusy = true;
    this.state.metrics.currentProject = prompt;

    const timestamp = Date.now();
    const taskId1 = `task-${timestamp}-1`;
    const taskId2 = `task-${timestamp}-2`;

    this.emitTerminal(
      'pm',
      `\r\n\x1b[1;33m⚡ [SPRINT TRIGGERED]\x1b[0m "${prompt}"\r\n` +
      `\x1b[38;5;244mDeconstructing requirements into atomic Kanban tickets...\x1b[0m\r\n`
    );

    // 1. Michael walks to conference room
    const pm = this.state.agents.pm;
    pm.currentAction = 'Walking to conference room...';
    await this.animateWalk('pm', { x: 180, y: 140 }, 8, 40);

    pm.status = 'PLANNING';
    pm.currentAction = 'PM: Planning sprint architecture';
    pm.actionProgress = 40;
    this.notifyState();
    await this.sleep(600);

    // Add 2 Kanban cards
    const newTask1: Task = {
      id: taskId1,
      title: `Implement Core Engine for ${prompt.slice(0, 30)}`,
      description: 'Author type-safe service modules and export contract interfaces in ./workspace.',
      status: 'BACKLOG',
      assignedAgentId: 'coder',
      priority: 'HIGH',
      files: ['src/analytics/engine.ts'],
      createdAt: timestamp,
      reviewNotes: [],
    };

    const newTask2: Task = {
      id: taskId2,
      title: `Build Component & Dashboard for ${prompt.slice(0, 25)}`,
      description: 'Create reactive SVG visualizer with telemetry meters and hover state.',
      status: 'BACKLOG',
      assignedAgentId: 'coder',
      priority: 'MEDIUM',
      files: ['src/components/AnalyticsWidget.tsx'],
      createdAt: timestamp + 10,
      reviewNotes: [],
    };

    this.state.tasks.unshift(newTask2);
    this.state.tasks.unshift(newTask1);
    this.state.metrics.totalTasks = this.state.tasks.length;
    this.state.metrics.totalTokens += 850;
    this.state.metrics.totalCost += 0.0025;
    this.notifyState();

    this.emitTerminal('pm', `  \x1b[32m✔\x1b[0m Created Task [${taskId1}]: \x1b[1m${newTask1.title}\x1b[0m\r\n`);
    this.emitTerminal('pm', `  \x1b[32m✔\x1b[0m Created Task [${taskId2}]: \x1b[1m${newTask2.title}\x1b[0m\r\n`);

    this.sendMailboxMessage(
      'pm',
      'coder',
      `Sprint Task Assigned: ${newTask1.title}`,
      `Jim, please claim ${taskId1} and author code into ./workspace.`,
      'TASK_ASSIGNED',
      taskId1
    );

    await this.sleep(400);
    pm.currentAction = 'Returning to desk...';
    await this.animateWalk('pm', pm.homeCoordinates, 8, 40);
    pm.status = 'IDLE';
    pm.currentAction = 'Monitoring team velocity';
    this.notifyState();

    // 2. Jim Halpert Claims Task 1
    const coder = this.state.agents.coder;
    newTask1.status = 'IN_PROGRESS';
    this.state.metrics.gitBranch = `feature/${taskId1}`;
    coder.currentTaskId = taskId1;
    coder.currentAction = 'Jim: writing engine.ts [28%]';
    coder.actionProgress = 28;
    coder.status = 'CODING';
    this.notifyState();

    this.emitTerminal(
      'coder',
      `\r\n\x1b[1;32m▶ [CODER JIM] Claimed Task: ${newTask1.title}\x1b[0m\r\n` +
      `\x1b[38;5;244mBranch: feature/${taskId1} | Target: src/analytics/engine.ts\x1b[0m\r\n`
    );

    // Simulated typewriter code output
    const codeLines = [
      'export interface MetricEvent { id: string; name: string; value: number; }',
      'export class AnalyticsAggregator {',
      '  private buffer: MetricEvent[] = [];',
      '  public track(name: string, value: number) { this.buffer.push({ id: "evt-1", name, value }); }',
      '  public getP99Latency(): number { return 3.8; }',
      '}',
    ];

    for (let i = 0; i < codeLines.length; i++) {
      this.emitTerminal('coder', `  \x1b[38;5;250m${codeLines[i]}\x1b[0m\r\n`);
      coder.actionProgress = Math.round(((i + 1) / codeLines.length) * 100);
      coder.currentAction = `Jim: writing engine.ts [${coder.actionProgress}%]`;
      this.notifyState();
      await this.sleep(120);
    }

    this.virtualFiles['src/analytics/engine.ts'] = DEFAULT_VIRTUAL_FILES['src/analytics/engine.ts'];
    coder.tokensUsed += 640;
    this.state.metrics.totalTokens += 640;
    this.state.metrics.totalCost += 0.0019;
    newTask1.status = 'REVIEW';
    newTask1.diff = `--- a/src/analytics/engine.ts\n+++ b/src/analytics/engine.ts\n@@ -0,0 +1,24 @@\n+export class AnalyticsAggregator { ... }`;
    coder.status = 'IDLE';
    coder.currentAction = 'Waiting for PR review';
    this.notifyState();

    this.emitTerminal('coder', `\x1b[32m✔ File written to ./workspace/src/analytics/engine.ts\x1b[0m\r\n`);

    this.sendMailboxMessage(
      'coder',
      'reviewer',
      `Code Review Request: ${newTask1.title}`,
      `Dwight, pull request ready for branch feature/${taskId1}. Please review AST diff.`,
      'CODE_REVIEW_REQUEST',
      taskId1
    );

    // 3. Dwight Schrute Reviews Code
    const reviewer = this.state.agents.reviewer;
    reviewer.currentAction = "Walking to Jim's desk...";
    await this.animateWalk('reviewer', { x: 455, y: 190 }, 6, 40);

    reviewer.status = 'TESTING';
    reviewer.currentAction = 'Dwight: inspecting AST security';
    reviewer.actionProgress = 70;
    this.notifyState();

    this.emitTerminal(
      'reviewer',
      `\r\n\x1b[1;33m🛡️ [QA DWIGHT] Commencing Code Audit for ${taskId1}\x1b[0m\r\n` +
      `  \x1b[32m✔\x1b[0m OWASP Injection scan: Passed\r\n` +
      `  \x1b[32m✔\x1b[0m Strict TypeScript AST typing: 0 warnings\r\n` +
      `  \x1b[32m✔\x1b[0m Memory leak bound: Verified buffer flush cap\r\n`
    );

    newTask1.reviewNotes = [
      'Strict typing compliance passed.',
      '0 memory leaks detected.',
      'Approved for production deployment.',
    ];
    reviewer.tokensUsed += 420;
    this.state.metrics.totalTokens += 420;
    this.notifyState();
    await this.sleep(500);

    reviewer.currentAction = 'Returning to QA desk...';
    await this.animateWalk('reviewer', reviewer.homeCoordinates, 6, 40);
    reviewer.status = 'IDLE';
    reviewer.currentAction = 'Auditing security gates';
    this.notifyState();

    this.sendMailboxMessage(
      'reviewer',
      'devops',
      `Deploy Ready: ${newTask1.title}`,
      `Task ${taskId1} passed Schrute QA. Proceed to deployment.`,
      'DEPLOY_READY',
      taskId1
    );

    // 4. Pam Beesly Deploys in Server Room
    const devops = this.state.agents.devops;
    devops.currentAction = 'Walking to server cluster...';
    await this.animateWalk('devops', { x: 740, y: 320 }, 8, 40);

    devops.status = 'DEPLOYING';
    devops.currentAction = 'Pam: executing test runner & build';
    devops.actionProgress = 85;
    this.notifyState();

    this.emitTerminal(
      'devops',
      `\r\n\x1b[1;35m🚀 [DEVOPS PAM] Running test suite in server cluster\x1b[0m\r\n` +
      `\x1b[36m$ npm test --prefix ./workspace\x1b[0m\r\n` +
      `  \x1b[32m✔ PASS\x1b[0m tests/analytics.test.ts (12/12 passed)\r\n` +
      `\x1b[36m$ git checkout main && git merge feature/${taskId1}\x1b[0m\r\n`
    );

    await this.sleep(500);
    newTask1.status = 'DONE';
    newTask1.completedAt = Date.now();
    newTask1.testResults = { passed: true, output: '12/12 test suites passed (100% coverage).' };
    this.state.metrics.completedTasks = this.state.tasks.filter((t) => t.status === 'DONE').length;
    this.state.metrics.gitBranch = 'main';
    devops.tokensUsed += 380;
    this.state.metrics.totalTokens += 380;
    this.state.metrics.totalCost += 0.0012;
    this.notifyState();

    this.emitTerminal('devops', `\x1b[1;32m✔ Release completed for [${taskId1}]! Merged to main.\x1b[0m\r\n`);

    devops.currentAction = 'Returning to DevOps desk...';
    await this.animateWalk('devops', devops.homeCoordinates, 8, 40);
    devops.status = 'IDLE';
    devops.currentAction = 'Monitoring cluster status';
    this.notifyState();

    this.isBusy = false;
  }

  public togglePause(): void {
    this.state.metrics.isPaused = !this.state.metrics.isPaused;
    this.notifyState();
  }

  public reset(): void {
    this.state = this.createInitialState();
    this.mailbox = [];
    this.virtualFiles = { ...DEFAULT_VIRTUAL_FILES };
    this.startTime = Date.now();
    this.notifyState();
    this.emitTerminal('pm', `\r\n\x1b[1;33m🔄 OfficeDev simulation reset. Ready for next sprint.\x1b[0m\r\n`);
  }

  public listFiles(): FileTreeNode[] {
    const root: FileTreeNode = {
      name: 'workspace',
      path: '/workspace',
      relativePath: '',
      type: 'directory',
      children: [
        {
          name: 'README.md',
          path: '/workspace/README.md',
          relativePath: 'README.md',
          type: 'file',
          size: 462,
          extension: '.md',
        },
        {
          name: 'package.json',
          path: '/workspace/package.json',
          relativePath: 'package.json',
          type: 'file',
          size: 280,
          extension: '.json',
        },
        {
          name: 'src',
          path: '/workspace/src',
          relativePath: 'src',
          type: 'directory',
          children: [
            {
              name: 'analytics',
              path: '/workspace/src/analytics',
              relativePath: 'src/analytics',
              type: 'directory',
              children: [
                {
                  name: 'engine.ts',
                  path: '/workspace/src/analytics/engine.ts',
                  relativePath: 'src/analytics/engine.ts',
                  type: 'file',
                  size: 1012,
                  extension: '.ts',
                },
              ],
            },
            {
              name: 'components',
              path: '/workspace/src/components',
              relativePath: 'src/components',
              type: 'directory',
              children: [
                {
                  name: 'AnalyticsWidget.tsx',
                  path: '/workspace/src/components/AnalyticsWidget.tsx',
                  relativePath: 'src/components/AnalyticsWidget.tsx',
                  type: 'file',
                  size: 1548,
                  extension: '.tsx',
                },
              ],
            },
          ],
        },
      ],
    };

    return root.children || [];
  }

  public readFile(relativePath: string): string {
    return this.virtualFiles[relativePath] || `// File content for ${relativePath}\n// Synthesized by MunderDifflin`;
  }
}

// Global Singleton for Client-Side Simulation
let clientOrchestratorInstance: ClientOrchestrator | null = null;

export function getClientOrchestrator(): ClientOrchestrator {
  if (!clientOrchestratorInstance) {
    clientOrchestratorInstance = new ClientOrchestrator();
  }
  return clientOrchestratorInstance;
}
